name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Publish
        run: >
          dotnet publish -c Release /p:Platform="Any CPU"
          /p:Sts2DataDir="$STS2_DATA_DIR"
          /p:GodotPath="$GODOT_PATH"
          /p:ModsPath="${{ github.workspace }}/output/mods/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AscensionTracker-publish
          path: output/mods/AscensionTracker/
